services:
  server:
    image: teamonemg/tt-server:test2
    container_name: testTT
    environment:
      - SPRING_PROFILES_ACTIVE=mariadb
      - SPRING_DATASOURCE_URL=jdbc:mariadb://testDBContainer:3306/testdb
      - SPRING_DATASOURCE_USERNAME=testuser
      - SPRING_DATASOURCE_PASSWORD=232323
    networks:
      - testnet
    ports:
      - 8080:8080
    restart: no

networks:
  testnet:
    external: true