#여기있는 파일이 동작하는게 아님 실제 docker compose는 따로 존재함
services:
  server:
    image: teamonemg/tt-server:latest
    container_name: testTT
    environment:
      - SPRING_PROFILES_ACTIVE=mariadb
      - SPRING_DATASOURCE_URL=jdbc:mariadb://testDBContainer:3306/testdb
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - spring.jwt.secret=
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - chat.system=
    volumes:
      - ~/test/testTT-log:/var/log/testTT-log
    networks:
      - testnet
    ports:
      - 8080:8080
    restart: no

networks:
  testnet:
    external: true