#여기있는 파일이 동작하는게 아님 실제 docker compose는 따로 존재함
services:
  server:
    image: demo:latest
    container_name: demoTT
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ~/test/testTT-log:/var/log/testTT-log
      - ~/test/config/:/var/config/ #application-secret.yml 파일 및 각종 설정 파일 바인딩 마운트
    networks:
      - testnet
    ports:
      - 8080:8080
    restart: no

networks:
  testnet:
    external: true