spring:
  profiles:
    default: default
  config:
    import: optional:application-secret.yml

  jpa:
    hibernate:
      #이걸 create로 바꾸시면 JPA가 테이블을 만들어줍니다
      #create로 한 번 돌리시고 반드시 none으로 바꿔야 합니다
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
  #ControllerAdvice를 통해 만들어지는 응답은 무시하기 위한 설정 (이거 필수)
  override-with-generic-response: false

firebase.admin.path: src/main/resources/firebase/admin.json

---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:/var/config/application-secret.yml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    path: /var/log/testTT-log

firebase.admin.path: /var/config/firebase/admin.json

