spring:
  #AWS의 MySQL
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://3.36.232.149:3306/tt-db
  #    username: tt-dev
  #    password: 232323

  #내 h2 DB
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:tcp://localhost/~/inflearn/h2/DB/testChat
  #    username: sa
  #    password:

  jpa:
    hibernate:
      #이걸 create로 바꾸시면 JPA가 테이블을 만들어줍니다
      #create로 한 번 돌리시고 반드시 none으로 바꿔야 합니다
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    websocket:
      message-broker:
        enabled: true     # WebSocket 메시지 브로커 활성화

    server:
      port: 8080            # 서버 포트 설정
      servlet:
        context-path: /chat # 애플리케이션 루트 경로 설정

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    #ControllerAdvice를 통해 만들어지는 응답은 무시하기 위한 설정 (이거 필수)
  override-with-generic-response: false


spring.jwt.secret: "qwfnlfasfdfapdzdflaksfalalasfjlasdifoasdfjl"


#server:
#  address: 0.0.0.0
#  port: 8080
